# Generated by Django 4.2.17 on 2025-10-06 15:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_onlinestatus_alter_quantumuser_kyber_private_key_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActiveEavesdropper",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "eavesdropper_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "injected_by",
                    models.CharField(
                        help_text="Email or identifier of entity that injected eavesdropper",
                        max_length=255,
                    ),
                ),
                (
                    "intercept_probability",
                    models.FloatField(
                        default=0.5,
                        help_text="Probability of intercepting each qubit (0.0 to 1.0)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether eavesdropper is currently active",
                    ),
                ),
                (
                    "sessions_intercepted",
                    models.IntegerField(
                        default=0,
                        help_text="Total number of BB84 sessions this eavesdropper has intercepted",
                    ),
                ),
                (
                    "total_qubits_intercepted",
                    models.IntegerField(
                        default=0,
                        help_text="Total number of qubits intercepted across all sessions",
                    ),
                ),
                (
                    "detections_count",
                    models.IntegerField(
                        default=0,
                        help_text="Number of times this eavesdropper was detected",
                    ),
                ),
                ("activated_at", models.DateTimeField(auto_now_add=True)),
                ("deactivated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Active Eavesdropper",
                "verbose_name_plural": "Active Eavesdroppers",
                "db_table": "active_eavesdropper",
            },
        ),
        migrations.AddField(
            model_name="bb84session",
            name="accepted_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when receiver accepted the session",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="bb84session",
            name="current_phase",
            field=models.CharField(
                blank=True,
                help_text="Current phase of BB84 protocol for real-time display",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="bb84session",
            name="eavesdropper_injected_by",
            field=models.CharField(
                blank=True,
                help_text="Email/ID of external entity that injected eavesdropper",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="bb84session",
            name="phase_timeline",
            field=models.JSONField(
                blank=True,
                help_text="Timeline of BB84 protocol phases with timestamps",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="bb84session",
            name="progress_percentage",
            field=models.IntegerField(
                default=0, help_text="Progress percentage (0-100) for UI display"
            ),
        ),
        migrations.AddField(
            model_name="bb84session",
            name="receiver_accepted",
            field=models.BooleanField(
                default=False,
                help_text="Whether receiver has accepted this BB84 session request",
            ),
        ),
        migrations.AlterField(
            model_name="bb84session",
            name="eavesdropper_present",
            field=models.BooleanField(
                default=False,
                help_text="Simulate eavesdropper (Eve) - controlled by external script/API only",
            ),
        ),
        migrations.AlterField(
            model_name="bb84session",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending - Waiting for receiver acceptance"),
                    ("accepted", "Accepted - Preparing key exchange"),
                    ("transmitting", "Transmitting - Quantum states in transit"),
                    ("sifting", "Sifting - Reconciling measurement bases"),
                    ("checking", "Checking - Verifying error rate"),
                    ("completed", "Completed - Shared key established"),
                    (
                        "failed",
                        "Failed - Eavesdropping detected or error threshold exceeded",
                    ),
                    ("aborted", "Aborted - Session cancelled by user"),
                    ("expired", "Expired - Session timeout"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
