# Generated by Django 4.2.17 on 2025-10-07 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_add_context_to_bb84session"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bb84session",
            name="expires_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Session expiration - DISABLED (permanent keys)",
                null=True,
            ),
        ),
    ]
