# Generated by Django 5.2.7 on 2025-10-07 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_bb84session_expires_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="bb84session",
            name="force_eavesdrop",
            field=models.BooleanField(
                default=False,
                help_text="Force active eavesdropper to intercept this session (UI override)",
            ),
        ),
    ]
